package com.google.android.gms.internal;

import android.support.annotation.NonNull;
import com.google.android.gms.common.api.OptionalPendingResult;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import com.google.android.gms.common.api.ResultTransform;
import com.google.android.gms.common.api.TransformedResult;
import java.util.concurrent.TimeUnit;

public final class zzox<R extends Result> extends OptionalPendingResult<R> {
    private final zznv<R> zzaoy;

    public zzox(PendingResult<R> pendingResult) {
        if (pendingResult instanceof zznv) {
            this.zzaoy = (zznv) pendingResult;
            return;
        }
        throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
    }

    public R await() {
        return this.zzaoy.await();
    }

    public R await(long j, TimeUnit timeUnit) {
        return this.zzaoy.await(j, timeUnit);
    }

    public void cancel() {
        this.zzaoy.cancel();
    }

    public R get() {
        if (isDone()) {
            return await(0, TimeUnit.MILLISECONDS);
        }
        throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
    }

    public boolean isCanceled() {
        return this.zzaoy.isCanceled();
    }

    public boolean isDone() {
        return this.zzaoy.isReady();
    }

    public void setResultCallback(ResultCallback<? super R> resultCallback) {
        this.zzaoy.setResultCallback(resultCallback);
    }

    public void setResultCallback(ResultCallback<? super R> resultCallback, long j, TimeUnit timeUnit) {
        this.zzaoy.setResultCallback(resultCallback, j, timeUnit);
    }

    @NonNull
    public <S extends Result> TransformedResult<S> then(@NonNull ResultTransform<? super R, ? extends S> resultTransform) {
        return this.zzaoy.then(resultTransform);
    }

    public void zza(PendingResult.zza zza) {
        this.zzaoy.zza(zza);
    }

    public Integer zzrv() {
        return this.zzaoy.zzrv();
    }
}
